<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Version>1.0.2</Version>
        <Authors>Ben Hutchison</Authors>
        <Copyright>© 2026 $(Authors)</Copyright>
        <Company>$(Authors)</Company>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>true</ImplicitUsings>

        <PackageProjectUrl>https://github.com/Aldaviva/SolCalc</PackageProjectUrl>
        <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
        <PackageReleaseNotes>$(PackageProjectUrl)/releases/tag/$(Version)</PackageReleaseNotes>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <Description>Find when sunrise, sunset, and different twilights happen for a given location, based on the NOAA ESRL Solar Calculator. Features high accuracy across several millenia, atmospheric refraction, a simple enumeration-based API, and multiple/missing events during polar night/day/twilight at extreme latitudes.</Description>
        <PackageTags>sun solar day daylight daytime night nighttime civil nautical astronomical twilight sunrise sunset dawn daybreak dusk morning evening azimuth elevation noon time</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeSource>true</IncludeSource>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PackageIcon>icon.jpg</PackageIcon>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
        <WarningsAsErrors>CA1859</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.203" PrivateAssets="All" />
        <PackageReference Include="NodaTime" Version="3.3.2" />
        <PackageReference Include="Unfucked" Version="0.0.1-beta.43" NoWarn="NU5104" />
        <PackageReference Include="Unfucked.DateTime" Version="0.0.1-beta.5" NoWarn="NU5104" />
    </ItemGroup>

    <ItemGroup>
        <None Include="icon.jpg;..\Readme.md" Pack="true" PackagePath="\" />
        <None Include="..\.github*\**" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Tests;Performance" />
    </ItemGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true' or '$(Configuration)' != 'Debug'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

</Project>